### ISSUE TITLE
Date Debut not working ?

### ISSUE THREAD

**Issue by grantime** [igeofr/mapillary2pg#1]
Hello i'm trying your script and i think i have an issue for the date parameter. 
Maybe i'm doing something wrong ?
 
it return the following error ==> "mapillary_vt2pg.sh: 48: -d: not found"

**Comment by igeofr** [comment]
Hello,
You have completed the environment file : config.env?

**Comment by grantime** [comment]
Yes! the date has to be a real "debut" of sequence ? can it be something like in config file.

**Comment by igeofr** [comment]
Thanks. I corrected the code.
Line 48 : `DATE_EPOCH=$(date -d $DATE_DEBUT +%s)`
